### ISSUE TITLE
initial setup troubles

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/makepdf#1]
I am trying out this package. I could not run the transformation, probably due to some mistake from me and not the package. But maybe others will think the same way and figuring out my mistakes could help improving the readme.

I have added this path to driver.xml:
```
<xi:include xmlns:xi="http://www.w3.org/2001/XInclude"
      href="C:/Users/Dorothea/Documents/BetMas/Manuscripts/OxfordBodleian/Juel-Jensen/BDLaethb4.xml">
      <xi:fallback>
         BDLaethb4
      </xi:fallback>
   </xi:include>
```
My settings are as in the image of the readme. I changed nothing else in driver.xml.
When I click on the red transformation button, no transformation model is selected (and none is called simply "PDF").  Should I choose one of the selected ones, or did something go wrong during my setup?

(And I get a schema error in driver.xml for `xmlns:t="http://www.tei-c.org/ns/1.0" type="mss" xml:id="AddisAbabaManuscripts"` attribute "type" not allowed here)

Thank you!

**Comment by PietroLiuzzo** [comment]
mmm... the transformation scenario is called catalogue2PDF I thought the setting would be preserved. can you tell me if you see that in the project?

**Comment by PietroLiuzzo** [comment]
as for the error in driver:
- you are probably defaulting your validation to BM schema? otherwise the teiCorpus file (driver.xml) does not have a schema association. 
- on the other side that type attribute is unnecessary, it can be removed with no harm or changed if you prefer

**Comment by thea-m** [comment]
I don't think so...
![image](https://user-images.githubusercontent.com/19650382/104173285-d2045100-5405-11eb-9ff9-777041c8707a.png)
I cloned the repository from GitHub and manually copied the fonts in the font folder.

**Comment by PietroLiuzzo** [comment]
I am not sure what your last comment refers to, sorry.
transformation scenarios are selected clicking on this icon with driver.xml in view.
<img width="128" alt="Schermata 2021-01-11 alle 12 12 08" src="https://user-images.githubusercontent.com/508012/104173600-5525a700-5406-11eb-8e4c-c100108dc58b.png">
than the transformation should be listed there
<img width="360" alt="Schermata 2021-01-11 alle 12 12 19" src="https://user-images.githubusercontent.com/508012/104173612-5951c480-5406-11eb-99bf-a34d1e4e989c.png">

**Comment by thea-m** [comment]
Yes, that's what I tried. I thought you meant the repository by "in the project"
This is the beginning of my transformations list, I could not find "catalogue2pdf" there.
![image](https://user-images.githubusercontent.com/19650382/104174403-ca917780-5406-11eb-82f0-ccb86e1b4ba8.png)
![image](https://user-images.githubusercontent.com/19650382/104174733-e1d06500-5406-11eb-95eb-e1c03f6d813d.png)

**Comment by thea-m** [comment]
I don't seem to have "Project" subfolder in the transformations list:
![image](https://user-images.githubusercontent.com/19650382/104175884-2fe56880-5407-11eb-8bb6-0f1e0b8df5c9.png)

**Comment by PietroLiuzzo** [comment]
have you started from catalogue.xpr? or added the makePDF folder to another project?

**Comment by thea-m** [comment]
You're right, I added it to BetMas when I cloned it. I will try again and let you know.

**Comment by thea-m** [comment]
Yes, now I see the model. But the transformation failed - "Unsupported XQuery version 3.1". Maybe this is related to my old oxygen version (18.1)?

**Comment by PietroLiuzzo** [comment]
yes. no doubt. we have licences. please upgrade and I will send you the key.

**Comment by thea-m** [comment]
I did not want to waste one, since everything worked until now, but fine :)

**Comment by thea-m** [comment]
Works now, thank you!

**Comment by PietroLiuzzo** [comment]
cool! let me know how it goes from there.
