### ISSUE TITLE
Manuscript shelfmarks in header

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/makepdf#10]
We would like a header line in the catalogue that gives on the left (even pages) the title of the catalogue and on the right (odd pages) the shelfmark of the manuscript being described on that page (as in the Dayr as-Suryan catalogue, only with the content of the header of even and odd pages exchanged).
![image](https://github.com/BetaMasaheft/makepdf/assets/19650382/db694528-921c-464b-bdd8-0053f58b5ae0)

I have inserted the title of the book on all even pages, as it does not change, but I could not add a header with automatically changing shelfmarks on the odd pages.

I believe the corresponding excerpts from the DS catalogue .fo are:
      

> <fo:static-content flow-name="rest-region-before-even">
>             <fo:block-container height="100%" display-align="center">
>                 <fo:table>
>                     <fo:table-column column-width="30%"/>
>                     <fo:table-column column-width="40%"/>
>                     <fo:table-column column-width="30%"/>
>                     <fo:table-body>
>                         <fo:table-row>
>                             <fo:table-cell>
>                                 <fo:block font-size="9pt" font-family="Ludolfus" text-align="left"
>                                     ><fo:page-number/></fo:block>
>                             </fo:table-cell>
>                             <fo:table-cell>
>                                 <fo:block text-align="center" font-size="9pt" font-family="Ludolfus"
>                                     ><fo:retrieve-marker retrieve-class-name="msname" retrieve-boundary="page-sequence" retrieve-position="first-including-carryover"/></fo:block>
>                             </fo:table-cell>
>                             <fo:table-cell>
>                                 <fo:block font-size="9pt" font-family="Ludolfus" text-align="right"
>                                 />
>                             </fo:table-cell>
>                         </fo:table-row>
>                     </fo:table-body>
>                 </fo:table>
>             </fo:block-container>
>         </fo:static-content>

and the corresponding fo:marker in each manuscript description:

> <fo:marker marker-class-name="msname">DS Ethiop. 2</fo:marker>

I have not managed to insert this successfully manually in in the catalogue.fo´, and do not know how add a corresponding command in the PDF.xql.

**Comment by PietroLiuzzo** [comment]
I am going to point you to the right place in xql

**Comment by PietroLiuzzo** [comment]
I am not sure about the actual version of the code in use for the project. It may be different from the one in this repository.

I think, after a quick check at the script here, that this is the line you should look at updating

https://github.com/BetaMasaheft/makepdf/blob/2992807ffd349324efefc43eef5c28a89432f9e7/PDF.xql#L3438

$tl is the value of the top-left header for the main contents, aka the catalogue, $tr the top-right, although I notice some left/right issues in the code. In case you get it the wrong way around, simply switch the $tr and $tl values at L3440.

I have not tested (I am on the train) but I think changing the XPath to point to //msIdentifier/idno should do the trick. the variable $r is the current manuscript XML file. 

```xql
{let $tr := $r/tei:teiHeader//tei:msDesc//tei:msIdentifer/tei:idno/text()
            let $tl := 'title of the book'
            return fo:static($tr,$tl)}
```

This is passed to a function which prints this beside the page number. There you can also adapt the relative position of the page number 

https://github.com/BetaMasaheft/makepdf/blob/2992807ffd349324efefc43eef5c28a89432f9e7/PDF.xql#L2784
 
The same function is used to produce the  heading in other sections with different contents.

I hope I have understood your issue and this can help you, if not, let me know.

**Comment by eu-genia** [comment]
@PietroLiuzzo thank you.

@thea-m 
you can replace the function
fo:maincontents (from line 3433) as follows
```
declare function fo:maincontents(){
for $r in $local:entries
return
(<fo:page-sequence
            initial-page-number="auto-odd"
            master-reference="Aethiopica-master">
            {let $tl := fo:authorheader($r/ancestor::tei:teiCorpus/tei:teiHeader//tei:titleStmt/tei:author)
            let $tr := $r//tei:msDesc/tei:msIdentifier/tei:idno[not(@xml:lang)]/text()
            return fo:static($tr,$tl)}
         <fo:flow
                flow-name="xsl-region-body"
                font-size="10.5pt"
                line-height="12.5pt"
                font-family="Ludolfus"
                text-align="justify"
                hyphenate="true">
<!-- CATALOGUE     -->            
      {fo:msheader($r//tei:msDesc/tei:msIdentifier),
                                        <fo:block text-align="center" space-before="2mm" space-after="3mm">{$r//tei:titleStmt/tei:title[not(@xml:lang)]/text()}</fo:block>,
                               fo:SimpleMsStructure($r)
                               }
                  <!--  break  after Catalogue -->
                <fo:block  page-break-after="always"/>
            </fo:flow>
        </fo:page-sequence> )
};
```

and at the end of the file remove the variable at
`       case 'catalogue' return fo:maincontents()
`
I hope this gets what you wanted (each description starts at a new page though)

**Comment by thea-m** [comment]
Thank you both! Works well
