### ISSUE TITLE
visualisation of <term>

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/makepdf#12]
Empty `<term key="..."/>` is currently  visualised as "no title provided", e.g.
`a <term key="halo"/> and a <term key="codex"/> ` becomes "a no title provided and a no title provided".
If `<term>` is empty, the content of `<title> `in `<titleStmt>` in the corresponding authority file should be printed.

**Comment by PietroLiuzzo** [comment]
in which context? index? catalogue? It can be set to not use the function to print titles reading the api. 

https://github.com/BetaMasaheft/makepdf/blob/de35b3a2d316be29b45f0d9f74f8e170a6fbd5c5/PDF.xql#L99C1-L103C3

preferably the API (or the sources of that) should be fixed to return correctly if they do not.

**Comment by PietroLiuzzo** [comment]
or you can add an option here
https://github.com/BetaMasaheft/makepdf/blob/de35b3a2d316be29b45f0d9f74f8e170a6fbd5c5/PDF.xql#L187

to deal with node()/@key as well as node()/@ref, simply adding an if... then ... else

**Comment by thea-m** [comment]
Thank you for having a look at this! I haven't tested it yet – I am now listing the various issues and will not myself work on the necessary adjustments immediately. Obviously, feel completely free to ignore these issues :)

**Comment by PietroLiuzzo** [comment]
No worries, I am sorry that I cannot help much.
