### ISSUE TITLE
manuscript main data headline

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/makepdf#13]
In analogy to the Dayr as-Suryān catalogue, each manuscript description should start with one line of text (which follows the title line) giving the main data:

Material (value of `@key` in `<material>` in `<support>`) form (value of `@form` in `<objectDesc>`), XX × XX × XX (contents of  `<height>,  <width>,  <depth>` in `<dimensions type="outer" unit="mm">`) mm, XX g (content of `<measure type="weight" unit="g">`), XX (content of `<measure unit="leaf">` in `<extent>`) fols, XX (content of `<measure unit="quire">` in `<extent>`) quires, dating (content of `<origDate>` in `<history>`).

In the case of composite manuscripts (records having several `<msPart>`), the content of this headline should be defined:

-  for all items preceding the dating as taking the first occurrence of this element in the record (of the common `<physDesc>`, not the `<physDesc>`s pertaining to each `<msPart>`)
- followed by "Unit 1: dating (content of `<origDate>` in `<history>` of msPart with xml:id p1)", repeated as many times as there are msParts.

Material (value of `@key` in `<material>` in `<support>`) form (value of `@form` in `<objectDesc>`), composite, XX × XX × XX (contents of  `<height>,  <width>,  <depth>` in `<dimensions type="outer" unit="mm">`) mm, XX g (content of `<measure type="weight" unit="g">`), XX (content of `<measure unit="leaf">` in `<extent>`) fols, XX (content of `<measure unit="quire">` in `<extent>`) quires. Unit 1: dating (content of `<origDate>` in `<history>` of msPart with xml:id p1). Unit 2: dating (content of `<origDate>` in `<history>` of msPart with xml:id p3).

Examples from DS catalogue: 
DS Ethiopic. 1: Parchment codex, 195 × 130 × 52 mm, 132 fols, 14 quires, mid-eighteenth/mid-nineteenth century.

DS Ethiopic. 3: Parchment codex, composite, 250 × 185 × 40 mm, 102 fols, 14 quires. Unit 1:
seventeenth century. Unit 2: seventeenth century.

**Comment by PietroLiuzzo** [comment]
Greetings from the monks at Dayr as-Suryān, where I have been last week during a trip to Egypt.
I believe, in general, the version of the script used for that catalogue is probably already more advanced than the basic one here. Retrieving that version of the PDF.xql script might make the work easier, if the results desired are more similar to that than to those obtained with the version in this repository. If you do not find them I can have a look in my old computer and perhaps make a branch here with that code.

**Comment by thea-m** [comment]
Thank you! Indeed I do not find the old PDF.xql. If it is no trouble for you that would be kind.
