### ISSUE TITLE
superfluous space surrounding marked up entities

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/makepdf#15]
superfluous space surrounding marked up entities e.g. `persName`s or `<hi>`
![image](https://github.com/BetaMasaheft/makepdf/assets/19650382/ccaecf78-c821-48c2-a06c-ef11c8e24283)

had to be fixed manually in the past

**Comment by PietroLiuzzo** [comment]
The spaces.xslt step of the transformation now also enforces normalization of space  (`normalize-space()`) within each element. Unfortunately I have not been able to make this work for space between elements (in this case between `<fo:inline>` and `<fo:basic-link>`, and it would not remove space which is entirely unwanted without removing spaces which are necessary between existing fo elements. At the moment, I still cannot figure out a clever solution for this issue.

**Comment by eu-genia** [comment]
For the moment it has been agreed to remove `fo:basic-link` (at the cost of suppressing active links)
