### ISSUE TITLE
rendering of handDesc

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/makepdf#18]
Additions to the current printing of the element `<handDesc>`:
In analogy to the rendering of e.g. `layout `, each `<handNote>` should be printed as a list item ("1) Hand 1: Fine and regular handwriting..." )
After the rendering of `<desc>`, in a new line each the following elements should be printed (still indented under the respective list number):
`<seg type="ink">` Should be printed as "Ink:" followed by the content in the same line.
`<seg type="rubrication">` Should be printed as "Rubrication:" followed by the content in the same line.
`<list type="abbreviations">` Should be printed as "Abbreviations:" followed by the content in the same line.

**Comment by PietroLiuzzo** [comment]
I have changed the behaviour for the group of handNotes from `fo:block` to `fo:list-block` and consequently made items of the contents.
`<locus>` of `<handNote>` is currently printed just after Hand 1. I have removed it.
`<seg type="script">` is currently printed just before `<desc>`. I have commented it out.
`<persName role='scribe'/>` and `<date>` within `handNote` are omitted in DS Catalogue. Should these be printed here somehow? 
`<note>` within `handNote` will be omitted as in DS catalogue, but I see a lot of content in some example ms.
Below a work in progress example, to make sure I am on the right path
<img width="783" alt="Schermata 2024-02-08 alle 21 37 13" src="https://github.com/BetaMasaheft/makepdf/assets/508012/74015d8a-b493-48bd-96fd-cd5c330b06b4">
