### ISSUE TITLE
element collation to be printed

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/makepdf#20]
The quire structure given in  `<collation>` should be printed as formulas ideally in the same way as in the DS catalogue.
In addition, if the element `<signatures>` is present, its content should be printed as text following the title "Quire structure" and preceding the quire formula.

**Comment by PietroLiuzzo** [comment]
I have removed `<signatures>` from "other details" (#24) and I have added it to the specified position within "Quire structure".

**Comment by PietroLiuzzo** [comment]
<img width="903" alt="Schermata 2024-02-08 alle 19 05 00" src="https://github.com/BetaMasaheft/makepdf/assets/508012/788db2e1-1184-4163-b305-ab67ab9a8e42">
