### ISSUE TITLE
element condition to be printed

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/makepdf#22]
The content of the element `<condition>` should be printed in analogy to the other sections of description (title "condition" in the same layout as e.g. "history", the content of the element as continuous text) following "other details", preceding "history".

**Comment by PietroLiuzzo** [comment]
This requires a bit more detail, please.

In the example BDLaethc14 you have

```
msDesc
    history
    condition
    msPart 1
        history
        condition
    msPart 2
        history
        condition
```

In the current module and equally in the one from the app used for the DS catalogue, all history was printed once for the entire ms, at the end, so this would be printed like this, to respect the two requisites

- before "history"
- after "other details"


```
msDesc intro
unit 1
    [...]
    other details
    condition unit 1
unit 2
    [...]
    other details
   condition unit 2
     
condition msDesc

history 
     msDesc
     unit 1
     unit 2
```

The sequence of 2 condition sections, of the second unit and of the manuscript, with the postponement of the latter, makes me wonder if I understood properly what you would like to have.

Here some alternative interpretations, if you can please point me to the correct one or to another which I could not think about

```
msDesc intro
condition msDesc

unit 1
    [...]
    other details
    condition unit 1

unit 2
    [...]
    other details
   condition unit 2
     
history 
     msDesc
     unit 1
     unit 2
``` 

or 

```
msDesc intro
condition msDesc

unit 1
    [...]
    other details
    condition unit 1
    history unit 1

unit 2
    [...]
    other details
   condition unit 2
   history unit 2
     
history 
     msDesc
``` 

or 

```
msDesc intro

unit 1
    [...]
    other details

unit 2
    [...]
    other details
     
condition
     msDesc
     unit 1
     unit 2

history 
     msDesc
     unit 1
     unit 2

```

**Comment by PietroLiuzzo** [comment]
same for #21
