### ISSUE TITLE
cb and pb

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/makepdf#23]
`<cb>` and `<pb>` should be printed in analogy to the DS catalogue, the respective column or folio+column number given in parantheses
`በረ<cb n="b"/>ከቱ፡`  : በረ(b)ከቱ፡ 
`ዘዓቢይ፤<pb n="256rb"/>ወልዑል፡ ` ዘዓቢይ፤ (fol. 256rb) ወልዑል፡

**Comment by PietroLiuzzo** [comment]
<img width="1127" alt="Schermata 2024-02-08 alle 14 58 04" src="https://github.com/BetaMasaheft/makepdf/assets/508012/8fd0c6bd-9055-4f0f-91ee-c2667f845bc9">
