### ISSUE TITLE
other details to be added

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/makepdf#24]
A section titled "Other details" should be added in analogy to the DS catalogue preceding the section "history".
It should contain, in individual paragraphs:

- The content of   `<p>` in  `<support>`  
- other items possibly still to be added

**Comment by PietroLiuzzo** [comment]
<img width="939" alt="Schermata 2024-02-08 alle 14 18 21" src="https://github.com/BetaMasaheft/makepdf/assets/508012/4f2b9408-8810-4d7c-b9fa-9acd7c4d79c3">

**Comment by PietroLiuzzo** [comment]
This section in the DS catalogue had a very specific selection of items, also specifically selected for some manuscripts.
The relevant section to edit in the PDF.xql file to manage these paragraphs (`fo:block`) is this
https://github.com/BetaMasaheft/makepdf/blob/133850a003683ccb1eaed77ee82b219506e3070e/PDF.xql#L2278C1-L2308C3
you can add the xpath to the selector and then specify what to do with the block below, copying from existing examples. I have not included the specifics of the DS catalogue here as they are linked to the DS manuscript files, e.g. `$part//tei:foliation[ancestor::tei:TEI[@xml:id='DSEthiop23']]`.
