### ISSUE TITLE
markup inside `<q>` 

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/makepdf#25]
markup inside `<q>` leads to wrong visualisation:
`<q xml:lang="gez"><persName ref="PRS9162TaklaHa"><roleName type="title">አቡነ፡</roleName>ተክለ፡ ሃይማኖት።</persName></q>` currently printed as  "Text in GǝʿǝzGǝʿǝzGǝʿǝzGǝʿǝz", should be printed "አቡነ፡ ተክለ፡ ሃይማኖት።"

**Comment by PietroLiuzzo** [comment]
<img width="1381" alt="Schermata 2024-02-08 alle 14 14 18" src="https://github.com/BetaMasaheft/makepdf/assets/508012/f5109a2d-91bf-467c-9ba7-ab99b9abcc85">
