### ISSUE TITLE
wikidata in ref leads to transformation error

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/makepdf#3]
The following mark up (which I think is guidelines conform) in a manuscript led to a transformation error. After I deleted the placeName , everything was fine.
`ዘ<placeName ref="wd:Q48338">ቂሳርያ፡</placeName>`
(BDLaethd17)

**Comment by PietroLiuzzo** [comment]
please, see the [readme](https://github.com/BetaMasaheft/makepdf), this is not supported. it needs to be replaced with a local list in driver.xml

**Comment by thea-m** [comment]
Thank you!
