### ISSUE TITLE
transformation failed

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/makepdf#4]
I have tried to carry out the transformation, but it failed with the following error message:
"404 Not Found for:            https://betamasaheft.eu/api/LOC6126WadinN/title/json. Found while            atomizing the result of a call to fo:printTitleID"
I commented out BM IDs in driver.xml, but then the same message returned with the BM IDs used in the records I listed in xi:include. 
The last time I tried this (with the same set-up and records) a few weeks ago everything worked well. Please let me know if you need more information. Thank you!

**Comment by PietroLiuzzo** [comment]
The API function returning the json titles is now restored, it was omitted in the release of the db.

**Comment by thea-m** [comment]
Thank you, it works now!
