### ISSUE TITLE
manuscript descriptions printed incompletely

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/makepdf#5]
In the printed manuscript descriptions, only the elements history, msContents and additions are printed, not, for instance, binding and decoration or anything other than additions from physDesc (all are present in the manuscript records and set to yes in settings.xml).

**Comment by PietroLiuzzo** [comment]
It would really help me if you could share setting.xml and driver.xml

**Comment by PietroLiuzzo** [comment]
at least 1 ms that I can use to try

**Comment by PietroLiuzzo** [comment]
I have tried with DSEthiop1 and have found some paths to be too simplified. This update to the script should read decoration, binding and some other sections which were not reachable before

**Comment by PietroLiuzzo** [comment]
if you pull this change it may overwrite you local changes. so if you changed this file already, I would suggest using File Diff before. otherwise fetching the updated script or simply replicating the minor change I have made in your copy should do.

**Comment by thea-m** [comment]
Thank you, they are printed now
