### ISSUE TITLE
FO

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/makepdf#6]
It would be useful to have access to both the PDF and FO after the transformation

**Comment by PietroLiuzzo** [comment]
You can either update catalogue.xpr from here or

- open driver.xml
- click on CONFIGURE TRANSFORMATION SCENARIO 
 
<img width="335" alt="Schermata 2022-01-13 alle 13 51 39" src="https://user-images.githubusercontent.com/508012/149333583-9b8ebfd9-7109-4b04-ac28-07b459cb2d9b.png">

- duplicate the project scenario catalogue2PDF
- edit the copy 
     - rename it catalogue2FO
     - click on FO processor
     - untick Perform FO processing
     - click on output
     - name the output file catalogue.fo
 - save 

Now, you can run one to get the PDF, only the one returning the FO or both, if you want, selecting them at the same time.

**Comment by thea-m** [comment]
Thank you, that's very helpful!
